### ISSUE TITLE
Remove console logs

### ISSUE THREAD

**Issue by philippeluickx** [i-like-robots/Responsive-Image-Placeholders#2]
Thumbs up for a nice library!

For use in production, best to remove the console log on line 23 in https://github.com/i-like-robots/Responsive-Image-Placeholders/blob/master/js/responsive-placeholder-images.js

>> console.log(attr.name);

**Comment by i-like-robots** [comment]
Good spot - very careless of me! Do you fancy submitting a PR for it?

**Comment by philippeluickx** [comment]
https://github.com/i-like-robots/Responsive-Image-Placeholders/pull/3
